<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>Files.QuickLook.Host</AssemblyName>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <QuickLookRuntime Condition="'$(QuickLookRuntime)' == ''">$(MSBuildThisFileDirectory)..\..\artifacts\quicklook\</QuickLookRuntime>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="QuickLook.Common"><HintPath>$(QuickLookRuntime)QuickLook.Common.dll</HintPath></Reference>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.333" PrivateAssets="all" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3912.50" />
  </ItemGroup>
</Project>
